import React,{useState,useMemo}from"react";
import{Search,Users,AlertCircle}from"lucide-react";
import{StudentAvatar}from"@/components/StudentAvatar";
import{StudentsPageSkeleton}from"@/components/Skeleton";
import{useStudents}from"@/hooks/useStudents";
interface St{id:number;fullname:string;email?:string;grade?:number|null;}
const SB:React.FC<{value:string;onChange:(v:string)=>void}>=({value,onChange})=>(<div className="relative w-full max-w-sm"><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" size={16}/><input type="text" value={value} onChange={e=>onChange(e.target.value)} placeholder="חיפוש תלמיד..." dir="rtl" className="w-full pr-9 pl-3 py-2 text-sm border border-gray-200 rounded-lg bg-white shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 placeholder:text-gray-400"/>{value&&<button onClick={()=>onChange("")} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400">x</button>}</div>);
const GB:React.FC<{grade?:number|null}>=({grade})=>{if(grade==null)return<span className="text-xs text-gray-400">-</span>;const c=grade>=85?"bg-emerald-100 text-emerald-700":grade>=70?"bg-blue-100 text-blue-700":grade>=55?"bg-amber-100 text-amber-700":"bg-red-100 text-red-700";return<span className={"px-2 py-0.5 rounded-lg text-xs font-semibold "+c}>{grade}</span>;};
const SC:React.FC<{student:St}>=({student})=>(<div className="flex items-center gap-3 px-4 py-3 rounded-xl border border-gray-100 bg-white hover:border-blue-200 hover:shadow-sm transition-all" dir="rtl"><StudentAvatar name={student.fullname} size="md"/><div className="flex-1 min-w-0"><p className="text-sm font-medium text-gray-800 truncate">{student.fullname}</p>{student.email&&<p className="text-xs text-gray-400 truncate">{student.email}</p>}</div><GB grade={student.grade}/></div>);
const StudentsPage:React.FC=()=>{const[q,setQ]=useState("");const{students,loading,error}=useStudents();const filtered=useMemo(()=>{if(!q.trim())return students;const lq=q.toLowerCase();return students.filter(s=>s.fullname.toLowerCase().includes(lq)||(s.email??"").toLowerCase().includes(lq));},[students,q]);if(loading)return<StudentsPageSkeleton/>;return(<div className="flex flex-col gap-4 p-4 max-w-2xl mx-auto" dir="rtl"><div className="flex items-center justify-between flex-wrap gap-3"><div><h1 className="text-lg font-bold text-gray-800">תלמידים</h1><p className="text-xs text-gray-400 mt-0.5">{filtered.length} מתוך {students.length} תלמידים</p></div><SB value={q} onChange={setQ}/></div>{error&&<div className="flex items-center gap-2 p-4 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm" dir="rtl"><AlertCircle size={16}/>{error}</div>}{!error&&(filtered.length===0?<div className="flex flex-col items-center py-16" dir="rtl"><Users className="text-gray-300 mb-3" size={40}/><p className="text-gray-500 text-sm">{q?"לא נמצאו: "+q:"אין תלמידים"}</p></div>:<div className="flex flex-col gap-2">{filtered.map(s=><SC key={s.id} student={s}/>)}</div>)}</div>);};
export default StudentsPage;
