const app=document.getElementById('app');
const bg={meeting:'#E8EDF5',vacation:'#DDF7EF',community:'#DDF5FA',trip:'#E3F6DA',activity:'#E7EEFF',deadline:'#FFF0D8',ceremony:'#FFF4C7',exam:'#FFE1E1',quiz:'#FFE8EE',other:'#F4EFE8'};
const ac={meeting:'#334155',vacation:'#0F766E',community:'#0E7490',trip:'#166534',activity:'#1D4ED8',deadline:'#C2410C',ceremony:'#A16207',exam:'#B91C1C',quiz:'#BE123C',other:'#8A5A24'};
const dayBase={'א׳':'ראשון','ב׳':'שני','ג׳':'שלישי','ד׳':'רביעי','ה׳':'חמישי','ו׳':'שישי','ש׳':'שבת'};
app.innerHTML='<nav class="monthNav" aria-label="ניווט חודשים"><button type="button" data-month="5">מאי</button><button type="button" data-month="6">יוני</button></nav><main class="list" id="list" aria-live="polite"></main>';
load();
async function load(){try{const d=await fetch('data/may-june-events.json?v=24785da',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('events');return r.json()});const ev=(d.events||[]).filter(isRealMayJune).sort(sortEvents);draw(ev);bindNav();markActive(5)}catch{document.getElementById('list').innerHTML='<div class="empty">לא נמצאו אירועים</div>'}}
function isRealMayJune(e){return e&&e.title&&typeof e.date==='string'&&/-(05|06)-/.test(e.date)}
function sortEvents(a,b){return(a.date+(a.startTime||'')+a.title).localeCompare(b.date+(b.startTime||'')+b.title)}
function bindNav(){document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{markActive(b.dataset.month);const t=document.querySelector(`[data-event-month="${b.dataset.month}"]`);if(t)t.scrollIntoView({behavior:'smooth',block:'start'});});}
function markActive(month){document.querySelectorAll('[data-month]').forEach(b=>b.classList.toggle('active',String(b.dataset.month)===String(month)));}
function draw(ev){const list=document.getElementById('list');if(!ev.length){list.innerHTML='<div class="empty">לא נמצאו אירועים</div>';return}list.innerHTML=ev.map(card).join('')}
function card(e){const d=new Date(e.date+'T12:00:00');const month=d.getMonth()+1;const day=dayPhrase(e.dayLabel,d);const date=e.dateLabel||new Intl.DateTimeFormat('he-IL',{day:'numeric',month:'long'}).format(d);const time=[e.startTime,e.endTime].filter(Boolean).join(' - ');const c=ac[e.type]||ac.other,b=bg[e.type]||bg.other;return `<article class="event oneLineEvent" data-event-month="${month}" style="--bg:${b};--c:${c}"><div class="dateLine"><span class="dayPremium">${esc(day)}</span><span class="datePremium">${esc(date)}</span></div>${time?`<div class="time">${esc(time)}</div>`:''}<div class="eventText">${esc(e.title)}</div></article>`}
function dayPhrase(label,d){if(!label)return new Intl.DateTimeFormat('he-IL',{weekday:'long'}).format(d);const p=String(label).split('–').map(x=>dayBase[x.trim()]||x.trim()).filter(Boolean);if(p.length===1)return p[0]==='שבת'?'שבת':'יום '+p[0];if(p.length===2)return 'ימים '+p[0]+' ו'+p[1];return 'ימים '+p[0]+' עד '+p[p.length-1]}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
