const app=document.getElementById('app');
const bg={exam:'#FEE2E2',quiz:'#FFE4E6',vacation:'#CCFBF1',trip:'#DCFCE7',activity:'#DBEAFE',club:'#EDE9FE',ceremony:'#FEF3C7',meeting:'#E2E8F0',deadline:'#FFEDD5',other:'#F5F5F4'};
const ac={exam:'#B91C1C',quiz:'#DC2626',vacation:'#0F766E',trip:'#15803D',activity:'#2563EB',club:'#7C3AED',ceremony:'#92400E',meeting:'#475569',deadline:'#C2410C',other:'#A16207'};
app.innerHTML='<main class="list" id="list"><div class="empty">טוען...</div></main>';
main();
async function main(){let events=[];try{const src=await fetch('data/source.json?cb='+Date.now(),{cache:'no-store'}).then(r=>r.json());events=await fromWorkbook(src);if(!events.length)events=await fromKnownTabs(src)}catch{}events=uniq(events).sort((a,b)=>(a.raw+a.time+a.title).localeCompare(b.raw+b.time+b.title));draw(events)}
async function fromWorkbook(src){try{await loadXlsx();const url=`https://docs.google.com/spreadsheets/d/${src.sheetId}/export?format=xlsx&cb=${Date.now()}`;const buf=await fetch(url,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('xlsx');return r.arrayBuffer()});const wb=XLSX.read(buf,{type:'array',cellDates:false});let out=[];wb.SheetNames.forEach(name=>{const rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,raw:false,defval:''});out=out.concat(parseRows(rows,name))});return out}catch{return[]}}
function loadXlsx(){return new Promise((ok,bad)=>{if(window.XLSX)return ok();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=ok;s.onerror=bad;document.head.appendChild(s)})}
async function fromKnownTabs(src){let gids=[...(src.candidateGids||[]),...(src.allKnownGids||[]),src.gid,'0'].filter(Boolean).map(String).filter((v,i,a)=>a.indexOf(v)===i);let all=[];for(const gid of gids){try{let t=await loadTab(src.sheetId,gid);all=all.concat(parseRows(cells(t),gid))}catch{}}return all}
function loadTab(id,gid){return new Promise((ok,bad)=>{let cb='c'+Date.now()+Math.random().toString(36).slice(2);window[cb]=r=>{delete window[cb];document.getElementById(cb)?.remove();r&&r.status==='ok'?ok(r.table):bad()};let s=document.createElement('script');s.id=cb;s.onerror=bad;s.src=`https://docs.google.com/spreadsheets/d/${id}/gviz/tq?gid=${gid}&tqx=out:json;responseHandler:${cb}&_=${Date.now()}`;document.body.appendChild(s)})}
function cells(t){return(t.rows||[]).map(r=>(r.c||[]).map(c=>c?String(c.f??c.v??'').trim():''))}
function parseRows(rows,source){let by={},out=[];for(let r of rows){for(let c=0;c<(r||[]).length;c++){let v=clean(r[c]);if(!v)continue;let d=date(v);if(d){by[c]=d;let rest=clean(v.replace(reDate(),'').replace(/^יום\s+\S+/,''));if(rest&&!skip(rest))out.push(make(rest,d,source));continue}if(by[c]&&!skip(v)){parts(v).forEach(p=>{p=clean(p);if(p&&!skip(p))out.push(make(p,by[c],source))})}}}return out}
function make(v,d,source){let tm=time(v);let title=clean(v.replace(/\(?\d{1,2}:\d{2}\s*[-–]\s*\d{1,2}:\d{2}\)?/,'').replace(/\(?\d{1,2}:\d{2}\)?/,'').replace(/^(מפגש|ישיבה|פעילות|אירוע)\s*[:\-–]?\s*/,'').trim())||v;return{title,raw:d,date:toDate(d),time:[tm[0],tm[1]].filter(Boolean).join(' - '),type:kind(v),note:'',source}}
function draw(arr){let list=document.getElementById('list');if(!arr.length){list.innerHTML='<div class="empty">לא נמצאו אירועים</div>';return}let groups={};arr.forEach(e=>{(groups[e.raw]||(groups[e.raw]=[])).push(e)});list.innerHTML=Object.entries(groups).map(([d,a])=>`<section class="day"><div class="dayHead"><div class="dayName">${fmtDay(a[0].date)}</div><div class="dateText">${fmtDate(a[0].date)}</div></div>${a.map(card).join('')}</section>`).join('')}
function card(e){let b=bg[e.type]||bg.other,c=ac[e.type]||ac.other;return`<article class="event" style="--bg:${b};--c:${c}">${e.time?`<div class="time">${esc(e.time)}</div>`:''}<div class="title">${esc(e.title)}</div></article>`}
function reDate(){return/(\d{1,2})[./](\d{1,2})(?:[./](\d{2,4}))?/}
function date(v){let m=String(v).match(reDate());if(!m)return'';let now=new Date(),base=now.getMonth()>=8?now.getFullYear():now.getFullYear()-1;let y=m[3]?(m[3].length===2?2000+ +m[3]:+m[3]):(+m[2]>=9?base:base+1);return`${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}
function toDate(s){let[a,b,c]=s.split('-').map(Number);return new Date(a,b-1,c)}
function time(v){let m=String(v).match(/(\d{1,2}:\d{2})\s*[-–]\s*(\d{1,2}:\d{2})/);if(m)return[m[1],m[2]];m=String(v).match(/(\d{1,2}:\d{2})/);return m?[m[1],'']:['','']}
function kind(v){v=String(v).toLowerCase();if(v.includes('מבחן'))return'exam';if(v.includes('בוחן')||v.includes('בחן'))return'quiz';if(v.includes('חופש')||v.includes('חופשה'))return'vacation';if(v.includes('טיול')||v.includes('סיור'))return'trip';if(v.includes('חוג'))return'club';if(v.includes('טקס'))return'ceremony';if(v.includes('מפגש')||v.includes('ישיבה'))return'meeting';if(v.includes('הגשה')||v.includes('יעד'))return'deadline';return'activity'}
function skip(v){v=clean(v);return!v||v.includes('לוח')||v.includes('גלישת טקסט')||v.includes('גודל גופן')||v.includes('כל חודש')||v.length<2}
function parts(v){return String(v).split(/\n|\r|•|▪|▫|;|\s{3,}/).filter(Boolean)}
function uniq(a){let s=new Set();return a.filter(e=>{let k=e.raw+'|'+e.title+'|'+e.time;if(s.has(k))return false;s.add(k);return true})}
function clean(s){return String(s||'').trim().replace(/\s+/g,' ')}
function fmtDay(d){return new Intl.DateTimeFormat('he-IL',{weekday:'long'}).format(d)}
function fmtDate(d){return new Intl.DateTimeFormat('he-IL',{day:'numeric',month:'long',year:'numeric'}).format(d)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
