const app=document.getElementById('app');
const bg={meeting:'#E8EDF5',vacation:'#FFF2C8',community:'#DDF5FA',trip:'#E3F6DA',activity:'#E7EEFF',deadline:'#FFEDD5',ceremony:'#FFF4C7',other:'#F4EFE8'};
const ac={meeting:'#334155',vacation:'#B45309',community:'#0E7490',trip:'#166534',activity:'#1D4ED8',deadline:'#C2410C',ceremony:'#A16207',other:'#8A5A24'};
const gradeStyle={z:{bg:'#FCE7F3',accent:'#BE185D'},h:{bg:'#E0F2FE',accent:'#0369A1'},t:{bg:'#DCFCE7',accent:'#15803D'},mixed:{bg:'#FEF3C7',accent:'#A16207'}};
const dayBase={'א׳':'ראשון','ב׳':'שני','ג׳':'שלישי','ד׳':'רביעי','ה׳':'חמישי','ו׳':'שישי','ש׳':'שבת'};
const screenTitles={home:'בחירת לוח',events:'לוח אירועים',exams:'לוח מבחנים',all:'אירועים ומבחנים'};
let state={mode:'home',items:[],examGrade:'all'};
startClock();
load();
window.addEventListener('hashchange',renderScreen);
async function load(){try{const [eventsData,examsData]=await Promise.all([fetchJson('data/may-june-events.json?v=865a901'),fetchJson('data/exams.json?v=c0eee5a')]);const events=(eventsData.events||[]).filter(isRealMayJune).map(e=>({...e,category:'event'}));const exams=groupExamsByDate((examsData.exams||[]).filter(isRealMayJune).map(normalizeExam));state.items=mergeItems(events,exams);renderScreen()}catch{app.innerHTML='<main class="list"><div class="empty">לא נמצאו אירועים</div></main>'}}
function currentMode(){const h=(location.hash||'#home').replace('#','');return ['events','exams','all'].includes(h)?h:'home'}
function renderScreen(){state.mode=currentMode();if(state.mode==='home')return renderHome();let items=state.items;if(state.mode==='exams')items=filterExamGrade(items.filter(e=>e.category==='exam'));if(state.mode==='events')items=items.filter(e=>e.category!=='exam');app.innerHTML=`<section class="screenBar"><a class="backHome" href="#home">בית</a><h2>${esc(screenTitles[state.mode])}</h2></section>${state.mode==='exams'?gradeNav():''}<nav class="monthNav" aria-label="ניווט חודשים"><button type="button" data-month="5">מאי</button><button type="button" data-month="6">יוני</button></nav><main class="list" id="list" aria-live="polite"></main>`;draw(items);bindGradeNav();bindMonthNav();}
function renderHome(){state.examGrade='all';app.innerHTML=`<main class="homeMenu" aria-label="בחירת לוח"><a class="homeCard eventsHome" href="#events"><span>לוח אירועים</span><small>אירועי החטיבה בלבד, ללא מבחנים</small></a><a class="homeCard examsHome" href="#exams"><span>לוח מבחנים</span><small>בחירה לפי שכבה או כל המבחנים</small></a><a class="homeCard allHome" href="#all"><span>אירועים ומבחנים</span><small>לוח מלא משולב לפי רצף תאריכים</small></a></main>`}
function gradeNav(){return '<nav class="gradeNav" aria-label="בחירת שכבה במבחנים"><button type="button" data-grade="all">כל המבחנים</button><button type="button" data-grade="z">שכבת ז׳</button><button type="button" data-grade="h">שכבת ח׳</button><button type="button" data-grade="t">שכבת ט׳</button></nav>'}
function bindGradeNav(){document.querySelectorAll('[data-grade]').forEach(b=>{b.classList.toggle('active',b.dataset.grade===state.examGrade);b.onclick=()=>{state.examGrade=b.dataset.grade;renderScreen()}})}
function filterExamGrade(items){if(state.examGrade==='all')return items;return items.filter(e=>(e.grades||[]).includes(state.examGrade))}
function startClock(){const t=document.getElementById('clockTime'),d=document.getElementById('clockDate');if(!t||!d)return;const tick=()=>{const now=new Date();t.textContent=new Intl.DateTimeFormat('he-IL',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(now);d.textContent=new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(now)};tick();setInterval(tick,1000)}
function fetchJson(url){return fetch(url,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(url);return r.json()}).catch(()=>({events:[],exams:[]}))}
function normalizeExam(e){const title=e.title||[e.subject,e.className,e.group,e.note].filter(Boolean).join(' — ');return{...e,category:'exam',type:e.type||'exam',title,grades:detectGrades(title+' '+(e.className||''))}}
function detectGrades(text){const s=String(text||'');const g=[];if(/ז׳|ז'|שכבה ז|שכבת ז/.test(s))g.push('z');if(/ח׳|ח'|שכבה ח|שכבת ח/.test(s))g.push('h');if(/ט׳|ט'|שכבה ט|שכבת ט/.test(s))g.push('t');return [...new Set(g)]}
function examGradeClass(grades){if(!grades||!grades.length)return'mixed';if(grades.length>1)return'mixed';return grades[0]}
function isRealMayJune(e){return e&&e.title&&typeof e.date==='string'&&/-(05|06)-/.test(e.date)}
function sortEvents(a,b){return(a.date+(a.startTime||'')+a.title).localeCompare(b.date+(b.startTime||'')+b.title)}
function mergeItems(events,exams){const groupedEvents=groupEventsByDate(events.sort(sortEvents));return[...groupedEvents,...exams.sort(sortEvents)].sort(sortEvents)}
function groupEventsByDate(events){const map=new Map();for(const e of events){const key=e.date+'|'+(e.dateLabel||'');if(!map.has(key)){map.set(key,{...e,titles:[],types:[],startTime:'',endTime:'',category:'event'})}const g=map.get(key);if(e.title&&!g.titles.includes(e.title))g.titles.push(e.title);if(e.type&&!g.types.includes(e.type))g.types.push(e.type)}return Array.from(map.values()).map(g=>{g.type=pickType(g.types);g.title=g.titles.join(' | ');return g})}
function groupExamsByDate(exams){const map=new Map();for(const e of exams){const key=e.date+'|'+(e.dateLabel||'');if(!map.has(key)){map.set(key,{...e,titles:[],types:['exam'],category:'exam',type:'exam',grades:[]})}const g=map.get(key);if(e.title&&!g.titles.includes(e.title))g.titles.push(e.title);g.grades=[...new Set([...(g.grades||[]),...(e.grades||[])])]}return Array.from(map.values()).map(g=>{g.title=g.titles.join(' | ');return g})}
function pickType(types){if(types.includes('vacation'))return'vacation';if(types.includes('trip'))return'trip';if(types.includes('ceremony'))return'ceremony';if(types.includes('meeting'))return'meeting';return types[0]||'other'}
function bindMonthNav(){document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-month]').forEach(x=>x.classList.toggle('active',x===b));const t=document.querySelector(`[data-event-month="${b.dataset.month}"]`);if(t)t.scrollIntoView({behavior:'smooth',block:'start'});});const first=document.querySelector('[data-month="5"]');if(first)first.classList.add('active')}
function draw(ev){const list=document.getElementById('list');if(!list)return;if(!ev.length){list.innerHTML=state.mode==='exams'?'<div class="empty">אין מבחנים בשכבה שנבחרה</div>':'<div class="empty">לא נמצאו אירועים</div>';return}list.innerHTML=ev.map(card).join('')}
function card(e){const d=new Date(e.date+'T12:00:00');const month=d.getMonth()+1;const day=dayPhrase(e.dayLabel,d);const date=e.dateLabel||new Intl.DateTimeFormat('he-IL',{day:'numeric',month:'long'}).format(d);const grade=examGradeClass(e.grades);const style=e.category==='exam'?(gradeStyle[grade]||gradeStyle.mixed):{bg:bg[e.type]||bg.other,accent:ac[e.type]||ac.other};const items=(e.titles&&e.titles.length?e.titles:[e.title]).map(t=>`<div class="eventItem">${esc(t)}</div>`).join('');const cls=['event','oneLineEvent',e.type==='vacation'?'vacationEvent':'',e.category==='exam'?'examEvent grade-'+grade:''].join(' ');return `<article class="${cls}" data-event-month="${month}" style="--bg:${style.bg};--c:${style.accent}"><div class="dateLine"><span class="dayPremium">${esc(day)}</span><span class="datePremium">${esc(date)}</span></div><div class="eventText">${items}</div></article>`}
function dayPhrase(label,d){if(!label)return new Intl.DateTimeFormat('he-IL',{weekday:'long'}).format(d);const p=String(label).split('–').map(x=>dayBase[x.trim()]||x.trim()).filter(Boolean);if(p.length===1)return p[0]==='שבת'?'שבת':'יום '+p[0];if(p.length===2)return 'ימים '+p[0]+' ו'+p[1];return 'ימים '+p[0]+' עד '+p[p.length-1]}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
