const app=document.getElementById('app');
let state={events:[],filter:'all',q:''};
const colors={exam:'#B91C1C',quiz:'#DC2626',vacation:'#0F766E',trip:'#15803D',activity:'#2563EB',club:'#7C3AED',special:'#BE185D',ceremony:'#92400E',meeting:'#475569',deadline:'#C2410C',community:'#0891B2',other:'#A16207'};
const labels={exam:'מבחן',quiz:'בוחן',vacation:'חופשה',trip:'טיול',activity:'פעילות',club:'חוג',special:'פעילות מיוחדת',ceremony:'טקס',meeting:'מפגש / ישיבה',deadline:'תאריך יעד',community:'קהילה / הורים',other:'אחר'};
boot();
function shell(){app.innerHTML='<header class="top" id="top"><h1>הצעה לניהול הלו״ז של חטיבת הביניים</h1><p id="status">טוען אירועים אמיתיים מהגיליון. אין באתר נתוני דמו.</p><div class="actions"><button id="refresh" type="button">רענן נתונים</button><a class="btn secondary" href="doctor.html?v=9364b5e">בדיקת גיליון</a></div></header><section class="search"><input id="q" type="search" placeholder="חיפוש באירועים שנשלפו מהקובץ"></section><nav class="chips" id="filters"><button class="on" data-type="all">הכול</button><button data-type="exam">מבחנים</button><button data-type="quiz">בחנים</button><button data-type="vacation">חופשות</button><button data-type="trip">טיולים</button><button data-type="ceremony">טקסים</button><button data-type="meeting">מפגשים</button></nav><div class="status" id="summary">ממתין לשליפה...</div><main class="list" id="list"></main><nav class="bottom"><a href="#top">למעלה</a><a href="#list">אירועים</a><a href="doctor.html?v=9364b5e">בדיקה</a><a href="health.html">בריאות</a></nav>'}
async function boot(){shell();bind();await sync()}
function bind(){document.getElementById('refresh').onclick=sync;document.getElementById('q').oninput=e=>{state.q=e.target.value.trim().toLowerCase();render()};document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#filters button').forEach(x=>x.classList.remove('on'));b.classList.add('on');state.filter=b.dataset.type;render()})}
async function sync(){setStatus('שולף נתונים מהגיליון...');try{const src=await fetch('data/source.json?cb='+Date.now(),{cache:'no-store'}).then(r=>r.json());const gids=[...(src.candidateGids||[]),src.gid,'0'].filter(Boolean).map(String).filter((v,i,a)=>a.indexOf(v)===i);let all=[],reports=[];for(const gid of gids){try{const table=await loadSheet(src.sheetId,gid);const events=extractEvents(table,gid);reports.push(`${gid}: ${events.length}`);all=all.concat(events)}catch(e){reports.push(`${gid}: שגיאה`)}}state.events=unique(all).sort((a,b)=>(a.dateRaw+a.startTime+a.title).localeCompare(b.dateRaw+b.startTime+b.title));setStatus(state.events.length?`נשלפו ${state.events.length} אירועים אמיתיים מהקובץ · ${reports.join(' · ')}`:`הקובץ נקרא, אבל לא זוהו אירועים. בדוק את דף הבדיקה.`);render()}catch(e){setStatus('לא ניתן לקרוא את מקור הנתונים. אין הצגת דמו.');state.events=[];render()}}
function loadSheet(id,gid){return new Promise((ok,bad)=>{const cb='stream_cb_'+Date.now()+Math.random().toString(36).slice(2);window[cb]=res=>{delete window[cb];document.getElementById(cb)?.remove();if(!res||res.status!=='ok')bad(new Error('not readable'));else ok(res.table)};const s=document.createElement('script');s.id=cb;s.onerror=()=>{delete window[cb];bad(new Error('load failed'))};s.src=`https://docs.google.com/spreadsheets/d/${id}/gviz/tq?gid=${gid}&tqx=out:json;responseHandler:${cb}&_=${Date.now()}`;document.body.appendChild(s)})}
function matrix(t){const head=(t.cols||[]).map(c=>clean(c.label||c.id||''));const rows=(t.rows||[]).map(r=>(r.c||[]).map(c=>c?String(c.f??c.v??'').trim():''));return[head,...rows]}
function extractEvents(table,gid){const m=matrix(table);const standard=extractStandard(m,gid);return standard.length?standard:extractGrid(m,gid)}
function extractStandard(m,gid){if(!m.length)return[];const h=m[0].map(clean);const hasDate=h.some(x=>['תאריך','date','Date'].includes(x));const hasTitle=h.some(x=>['שם אירוע','שם','אירוע','פעילות','title','Title'].includes(x));if(!hasDate||!hasTitle)return[];return m.slice(1).map(r=>{let o={};h.forEach((k,i)=>o[k]=r[i]||'');let title=pick(o,['שם אירוע','שם','אירוע','פעילות','title','Title']);let date=toDate(pick(o,['תאריך','date','Date']));if(!title||!date)return null;let text=[title,pick(o,['סוג','type','קטגוריה'])].join(' ');return{title,date:parseDate(date),dateRaw:date,type:typeKey(text),startTime:pick(o,['שעת התחלה','התחלה','startTime']),endTime:pick(o,['שעת סיום','סיום','endTime']),place:pick(o,['מיקום','מקום','location']),notes:pick(o,['הערות','notes','פרטים']),sourceGid:gid}}).filter(Boolean)}
function extractGrid(m,gid){let dateByCol={},out=[];for(let r=0;r<m.length;r++){for(let c=0;c<(m[r]||[]).length;c++){let raw=clean(m[r][c]);if(!raw)continue;let d=findDate(raw);if(d){dateByCol[c]=d;let rest=raw.replace(dateTokenRegex(),'').replace(/^יום\s+\S+/,'').trim();if(rest&&!skip(rest))out.push(makeEvent(rest,d,gid));continue}if(!dateByCol[c]||skip(raw))continue;splitCell(raw).forEach(p=>{p=clean(p);if(p&&!skip(p))out.push(makeEvent(p,dateByCol[c],gid))})}}return out}
function makeEvent(v,dateRaw,gid){let tm=time(v);let title=v.replace(/\(?\d{1,2}:\d{2}\s*[-–]\s*\d{1,2}:\d{2}\)?/,'').replace(/\(?\d{1,2}:\d{2}\)?/,'').trim()||v;return{title,date:parseDate(dateRaw),dateRaw,type:typeKey(v),startTime:tm[0],endTime:tm[1],place:'',notes:v===title?'':v,sourceGid:gid}}
function render(){const list=document.getElementById('list');const summary=document.getElementById('summary');let arr=state.events.filter(e=>(state.filter==='all'||e.type===state.filter)&&(!state.q||[e.title,e.notes,e.place,labels[e.type]].join(' ').toLowerCase().includes(state.q)));summary.textContent=arr.length?`מוצגים ${arr.length} אירועים אמיתיים`:'אין אירועים להצגה בסינון הנוכחי';if(!state.events.length){list.innerHTML='<div class="empty">לא זוהו אירועים אמיתיים מהקובץ. אין באתר דמו.</div>';return}let groups={};arr.forEach(e=>{let k=niceDate(e.date);(groups[k]||(groups[k]=[])).push(e)});list.innerHTML=Object.entries(groups).map(([d,items])=>`<section class="dayBlock"><div class="dayTitle">${esc(d)}</div>${items.map(card).join('')}</section>`).join('')||'<div class="empty">אין תוצאות לחיפוש הנוכחי.</div>'}
function card(e){return`<article class="event" style="--c:${colors[e.type]||colors.other}"><h2>${esc(e.title)}</h2><span class="badge">${esc(labels[e.type]||labels.other)}</span><div class="meta">${e.startTime?`<span>${esc([e.startTime,e.endTime].filter(Boolean).join(' - '))}</span>`:''}${e.place?`<span>${esc(e.place)}</span>`:''}<span>מקור: גיליון ${esc(e.sourceGid)}</span></div>${e.notes?`<div class="meta"><span>${esc(e.notes)}</span></div>`:''}</article>`}
function setStatus(t){document.getElementById('status').textContent=t}
function splitCell(v){return String(v).split(/\n|\r|•|▪|▫|;|\s{3,}/).filter(Boolean)}
function dateTokenRegex(){return /(\d{1,2})[./](\d{1,2})(?:[./](\d{2,4}))?/}
function findDate(v){let m=String(v||'').match(dateTokenRegex());if(!m)return'';let now=new Date(),base=now.getMonth()>=8?now.getFullYear():now.getFullYear()-1;let y=m[3]?(m[3].length===2?2000+Number(m[3]):Number(m[3])):(Number(m[2])>=9?base:base+1);return`${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}
function toDate(v){v=String(v||'').trim();let m=v.match(/^(\d{1,2})[./](\d{1,2})(?:[./](\d{2,4}))?$/);if(!m)return findDate(v);let now=new Date(),base=now.getMonth()>=8?now.getFullYear():now.getFullYear()-1;let y=m[3]?(m[3].length===2?2000+Number(m[3]):Number(m[3])):(Number(m[2])>=9?base:base+1);return`${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}
function parseDate(s){let[a,b,c]=s.split('-').map(Number);return new Date(a,b-1,c)}
function time(v){let m=String(v).match(/(\d{1,2}:\d{2})\s*[-–]\s*(\d{1,2}:\d{2})/);if(m)return[m[1],m[2]];m=String(v).match(/(\d{1,2}:\d{2})/);return m?[m[1],'']:['','']}
function typeKey(v){v=String(v).toLowerCase();if(v.includes('מבחן'))return'exam';if(v.includes('בוחן')||v.includes('בחן'))return'quiz';if(v.includes('חופש')||v.includes('חופשה'))return'vacation';if(v.includes('טיול')||v.includes('סיור'))return'trip';if(v.includes('חוג'))return'club';if(v.includes('טקס'))return'ceremony';if(v.includes('ישיבה')||v.includes('מפגש'))return'meeting';if(v.includes('הורים')||v.includes('קהילה'))return'community';if(v.includes('הגשה')||v.includes('תאריך יעד'))return'deadline';return'activity'}
function skip(v){v=clean(v);return !v||v.includes('לוח')||v.includes('גלישת טקסט')||v.includes('גודל גופן')||v.includes('כל חודש')||v.length<2}
function unique(a){const s=new Set();return a.filter(e=>{let k=e.dateRaw+'|'+e.title+'|'+e.startTime+'|'+e.endTime;if(s.has(k))return false;s.add(k);return true})}
function pick(o,names){for(const n of names){if(o[n])return o[n]}return''}
function niceDate(d){return new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(d)}
function clean(s){return String(s||'').trim().replace(/\s+/g,' ')}
function esc(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
