// AUTO-GENERATED by scripts/guide/optimize-screenshots.mjs — do not edit by hand.
// Intrinsic dimensions of each guide screenshot, used to reserve exact space
// (aspect-ratio + width/height) so images never cause layout shift (CLS = 0).
export type ShotDim = { w: number; h: number };

export const SHOT_META: Record<string, ShotDim> = {
  '01-login.jpg': { w: 1200, h: 569 },
  '02-my-courses-home.jpg': { w: 1200, h: 603 },
  '03-topbar-edit-off.png': { w: 400, h: 62 },
  '04-topbar-edit-on.png': { w: 400, h: 62 },
  '05-home-edit-on.jpg': { w: 1200, h: 603 },
  '06-course-edit-on.jpg': { w: 1200, h: 603 },
  '07-unit-menu.jpg': { w: 1200, h: 603 },
  '08-more-options.jpg': { w: 1200, h: 603 },
  '09-user-menu.jpg': { w: 1200, h: 603 },
  '10-course-page.jpg': { w: 1200, h: 603 },
  '11-notifications.jpg': { w: 1200, h: 603 },
  '12-messages.jpg': { w: 1200, h: 603 },
  '13-section-menu-full.jpg': { w: 1200, h: 603 },
  '14-hidden-items.jpg': { w: 1200, h: 603 },
  '15-add-activity-button.jpg': { w: 1200, h: 603 },
  '16-activity-chooser.jpg': { w: 1200, h: 603 },
  '17-activity-chooser-more.jpg': { w: 1200, h: 603 },
  '18-reports.jpg': { w: 1200, h: 603 },
  '19-wizard-step1.jpg': { w: 1200, h: 579 },
  '20-wizard-step1-selected.jpg': { w: 1200, h: 579 },
  '21-wizard-step1-form.jpg': { w: 1200, h: 579 },
  '22-wizard-step2.jpg': { w: 1200, h: 603 },
  '24-wizard-step4.jpg': { w: 1200, h: 603 },
  '25-wizard-step1-filled.jpg': { w: 1200, h: 603 },
  '26-selfenrol-methods-list.jpg': { w: 958, h: 854 },
  '27-selfenrol-settings.jpg': { w: 958, h: 854 },
  '28-selfenrol-student-view.jpg': { w: 958, h: 910 },
  '29-selfenrol-success-studentview.jpg': { w: 958, h: 910 },
  '30-student-mycourses-selflearning.jpg': { w: 958, h: 910 },
  '31-updates-drawer.jpg': { w: 958, h: 797 },
  '32-updates-list-expanded.jpg': { w: 958, h: 797 },
  '33-quiz-question-behaviour.jpg': { w: 958, h: 797 },
};
